//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package shared

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoveOperationProgress) DeepCopyInto(out *DataMoveOperationProgress) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompleteTime != nil {
		in, out := &in.CompleteTime, &out.CompleteTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoveOperationProgress.
func (in *DataMoveOperationProgress) DeepCopy() *DataMoveOperationProgress {
	if in == nil {
		return nil
	}
	out := new(DataMoveOperationProgress)
	in.DeepCopyInto(out)
	return out
}
