//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSISnapshotSpec) DeepCopyInto(out *CSISnapshotSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSISnapshotSpec.
func (in *CSISnapshotSpec) DeepCopy() *CSISnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(CSISnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotBackup) DeepCopyInto(out *SnapshotBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotBackup.
func (in *SnapshotBackup) DeepCopy() *SnapshotBackup {
	if in == nil {
		return nil
	}
	out := new(SnapshotBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotBackupList) DeepCopyInto(out *SnapshotBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SnapshotBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotBackupList.
func (in *SnapshotBackupList) DeepCopy() *SnapshotBackupList {
	if in == nil {
		return nil
	}
	out := new(SnapshotBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotBackupResult) DeepCopyInto(out *SnapshotBackupResult) {
	*out = *in
	if in.DataMoverResult != nil {
		in, out := &in.DataMoverResult, &out.DataMoverResult
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotBackupResult.
func (in *SnapshotBackupResult) DeepCopy() *SnapshotBackupResult {
	if in == nil {
		return nil
	}
	out := new(SnapshotBackupResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotBackupSpec) DeepCopyInto(out *SnapshotBackupSpec) {
	*out = *in
	if in.CSISnapshot != nil {
		in, out := &in.CSISnapshot, &out.CSISnapshot
		*out = new(CSISnapshotSpec)
		**out = **in
	}
	if in.DataMoverConfig != nil {
		in, out := &in.DataMoverConfig, &out.DataMoverConfig
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	out.OperationTimeout = in.OperationTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotBackupSpec.
func (in *SnapshotBackupSpec) DeepCopy() *SnapshotBackupSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotBackupStatus) DeepCopyInto(out *SnapshotBackupStatus) {
	*out = *in
	if in.DataMoverResult != nil {
		in, out := &in.DataMoverResult, &out.DataMoverResult
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	if in.StartTimestamp != nil {
		in, out := &in.StartTimestamp, &out.StartTimestamp
		*out = (*in).DeepCopy()
	}
	if in.CompletionTimestamp != nil {
		in, out := &in.CompletionTimestamp, &out.CompletionTimestamp
		*out = (*in).DeepCopy()
	}
	out.Progress = in.Progress
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotBackupStatus.
func (in *SnapshotBackupStatus) DeepCopy() *SnapshotBackupStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRestore) DeepCopyInto(out *SnapshotRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRestore.
func (in *SnapshotRestore) DeepCopy() *SnapshotRestore {
	if in == nil {
		return nil
	}
	out := new(SnapshotRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRestoreList) DeepCopyInto(out *SnapshotRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SnapshotRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRestoreList.
func (in *SnapshotRestoreList) DeepCopy() *SnapshotRestoreList {
	if in == nil {
		return nil
	}
	out := new(SnapshotRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRestoreSpec) DeepCopyInto(out *SnapshotRestoreSpec) {
	*out = *in
	out.TargetVolume = in.TargetVolume
	if in.DataMoverConfig != nil {
		in, out := &in.DataMoverConfig, &out.DataMoverConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.OperationTimeout = in.OperationTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRestoreSpec.
func (in *SnapshotRestoreSpec) DeepCopy() *SnapshotRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRestoreStatus) DeepCopyInto(out *SnapshotRestoreStatus) {
	*out = *in
	if in.StartTimestamp != nil {
		in, out := &in.StartTimestamp, &out.StartTimestamp
		*out = (*in).DeepCopy()
	}
	if in.CompletionTimestamp != nil {
		in, out := &in.CompletionTimestamp, &out.CompletionTimestamp
		*out = (*in).DeepCopy()
	}
	out.Progress = in.Progress
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRestoreStatus.
func (in *SnapshotRestoreStatus) DeepCopy() *SnapshotRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetVolumeSpec) DeepCopyInto(out *TargetVolumeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetVolumeSpec.
func (in *TargetVolumeSpec) DeepCopy() *TargetVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(TargetVolumeSpec)
	in.DeepCopyInto(out)
	return out
}
