// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	udmrepo "github.com/vmware-tanzu/velero/pkg/repository/udmrepo"
)

// NewMockObjectWriter creates a new instance of MockObjectWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectWriter {
	mock := &MockObjectWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectWriter is an autogenerated mock type for the ObjectWriter type
type MockObjectWriter struct {
	mock.Mock
}

type MockObjectWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectWriter) EXPECT() *MockObjectWriter_Expecter {
	return &MockObjectWriter_Expecter{mock: &_m.Mock}
}

// Checkpoint provides a mock function for the type MockObjectWriter
func (_mock *MockObjectWriter) Checkpoint() (udmrepo.ID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Checkpoint")
	}

	var r0 udmrepo.ID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (udmrepo.ID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() udmrepo.ID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(udmrepo.ID)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectWriter_Checkpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkpoint'
type MockObjectWriter_Checkpoint_Call struct {
	*mock.Call
}

// Checkpoint is a helper method to define mock.On call
func (_e *MockObjectWriter_Expecter) Checkpoint() *MockObjectWriter_Checkpoint_Call {
	return &MockObjectWriter_Checkpoint_Call{Call: _e.mock.On("Checkpoint")}
}

func (_c *MockObjectWriter_Checkpoint_Call) Run(run func()) *MockObjectWriter_Checkpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObjectWriter_Checkpoint_Call) Return(iD udmrepo.ID, err error) *MockObjectWriter_Checkpoint_Call {
	_c.Call.Return(iD, err)
	return _c
}

func (_c *MockObjectWriter_Checkpoint_Call) RunAndReturn(run func() (udmrepo.ID, error)) *MockObjectWriter_Checkpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockObjectWriter
func (_mock *MockObjectWriter) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectWriter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockObjectWriter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockObjectWriter_Expecter) Close() *MockObjectWriter_Close_Call {
	return &MockObjectWriter_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockObjectWriter_Close_Call) Run(run func()) *MockObjectWriter_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObjectWriter_Close_Call) Return(err error) *MockObjectWriter_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectWriter_Close_Call) RunAndReturn(run func() error) *MockObjectWriter_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Result provides a mock function for the type MockObjectWriter
func (_mock *MockObjectWriter) Result() (udmrepo.ID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Result")
	}

	var r0 udmrepo.ID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (udmrepo.ID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() udmrepo.ID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(udmrepo.ID)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectWriter_Result_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Result'
type MockObjectWriter_Result_Call struct {
	*mock.Call
}

// Result is a helper method to define mock.On call
func (_e *MockObjectWriter_Expecter) Result() *MockObjectWriter_Result_Call {
	return &MockObjectWriter_Result_Call{Call: _e.mock.On("Result")}
}

func (_c *MockObjectWriter_Result_Call) Run(run func()) *MockObjectWriter_Result_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObjectWriter_Result_Call) Return(iD udmrepo.ID, err error) *MockObjectWriter_Result_Call {
	_c.Call.Return(iD, err)
	return _c
}

func (_c *MockObjectWriter_Result_Call) RunAndReturn(run func() (udmrepo.ID, error)) *MockObjectWriter_Result_Call {
	_c.Call.Return(run)
	return _c
}

// Seek provides a mock function for the type MockObjectWriter
func (_mock *MockObjectWriter) Seek(offset int64, whence int) (int64, error) {
	ret := _mock.Called(offset, whence)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, int) (int64, error)); ok {
		return returnFunc(offset, whence)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, int) int64); ok {
		r0 = returnFunc(offset, whence)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = returnFunc(offset, whence)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectWriter_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type MockObjectWriter_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - offset int64
//   - whence int
func (_e *MockObjectWriter_Expecter) Seek(offset interface{}, whence interface{}) *MockObjectWriter_Seek_Call {
	return &MockObjectWriter_Seek_Call{Call: _e.mock.On("Seek", offset, whence)}
}

func (_c *MockObjectWriter_Seek_Call) Run(run func(offset int64, whence int)) *MockObjectWriter_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectWriter_Seek_Call) Return(n int64, err error) *MockObjectWriter_Seek_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockObjectWriter_Seek_Call) RunAndReturn(run func(offset int64, whence int) (int64, error)) *MockObjectWriter_Seek_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MockObjectWriter
func (_mock *MockObjectWriter) Write(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockObjectWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *MockObjectWriter_Expecter) Write(p interface{}) *MockObjectWriter_Write_Call {
	return &MockObjectWriter_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *MockObjectWriter_Write_Call) Run(run func(p []byte)) *MockObjectWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObjectWriter_Write_Call) Return(n int, err error) *MockObjectWriter_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockObjectWriter_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *MockObjectWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteAt provides a mock function for the type MockObjectWriter
func (_mock *MockObjectWriter) WriteAt(p []byte, off int64) (int, error) {
	ret := _mock.Called(p, off)

	if len(ret) == 0 {
		panic("no return value specified for WriteAt")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) (int, error)); ok {
		return returnFunc(p, off)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) int); ok {
		r0 = returnFunc(p, off)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, int64) error); ok {
		r1 = returnFunc(p, off)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectWriter_WriteAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteAt'
type MockObjectWriter_WriteAt_Call struct {
	*mock.Call
}

// WriteAt is a helper method to define mock.On call
//   - p []byte
//   - off int64
func (_e *MockObjectWriter_Expecter) WriteAt(p interface{}, off interface{}) *MockObjectWriter_WriteAt_Call {
	return &MockObjectWriter_WriteAt_Call{Call: _e.mock.On("WriteAt", p, off)}
}

func (_c *MockObjectWriter_WriteAt_Call) Run(run func(p []byte, off int64)) *MockObjectWriter_WriteAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectWriter_WriteAt_Call) Return(n int, err error) *MockObjectWriter_WriteAt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockObjectWriter_WriteAt_Call) RunAndReturn(run func(p []byte, off int64) (int, error)) *MockObjectWriter_WriteAt_Call {
	_c.Call.Return(run)
	return _c
}
