// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/kopia/kopia/repo/object"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// Checkpoint provides a mock function for the type MockWriter
func (_mock *MockWriter) Checkpoint() (object.ID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Checkpoint")
	}

	var r0 object.ID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (object.ID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() object.ID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(object.ID)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_Checkpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkpoint'
type MockWriter_Checkpoint_Call struct {
	*mock.Call
}

// Checkpoint is a helper method to define mock.On call
func (_e *MockWriter_Expecter) Checkpoint() *MockWriter_Checkpoint_Call {
	return &MockWriter_Checkpoint_Call{Call: _e.mock.On("Checkpoint")}
}

func (_c *MockWriter_Checkpoint_Call) Run(run func()) *MockWriter_Checkpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWriter_Checkpoint_Call) Return(iD object.ID, err error) *MockWriter_Checkpoint_Call {
	_c.Call.Return(iD, err)
	return _c
}

func (_c *MockWriter_Checkpoint_Call) RunAndReturn(run func() (object.ID, error)) *MockWriter_Checkpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockWriter
func (_mock *MockWriter) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockWriter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockWriter_Expecter) Close() *MockWriter_Close_Call {
	return &MockWriter_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockWriter_Close_Call) Run(run func()) *MockWriter_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWriter_Close_Call) Return(err error) *MockWriter_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_Close_Call) RunAndReturn(run func() error) *MockWriter_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Result provides a mock function for the type MockWriter
func (_mock *MockWriter) Result() (object.ID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Result")
	}

	var r0 object.ID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (object.ID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() object.ID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(object.ID)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_Result_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Result'
type MockWriter_Result_Call struct {
	*mock.Call
}

// Result is a helper method to define mock.On call
func (_e *MockWriter_Expecter) Result() *MockWriter_Result_Call {
	return &MockWriter_Result_Call{Call: _e.mock.On("Result")}
}

func (_c *MockWriter_Result_Call) Run(run func()) *MockWriter_Result_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWriter_Result_Call) Return(iD object.ID, err error) *MockWriter_Result_Call {
	_c.Call.Return(iD, err)
	return _c
}

func (_c *MockWriter_Result_Call) RunAndReturn(run func() (object.ID, error)) *MockWriter_Result_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MockWriter
func (_mock *MockWriter) Write(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *MockWriter_Expecter) Write(p interface{}) *MockWriter_Write_Call {
	return &MockWriter_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *MockWriter_Write_Call) Run(run func(p []byte)) *MockWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWriter_Write_Call) Return(n int, err error) *MockWriter_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockWriter_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *MockWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteAt provides a mock function for the type MockWriter
func (_mock *MockWriter) WriteAt(p []byte, off int64) (int, error) {
	ret := _mock.Called(p, off)

	if len(ret) == 0 {
		panic("no return value specified for WriteAt")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) (int, error)); ok {
		return returnFunc(p, off)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) int); ok {
		r0 = returnFunc(p, off)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, int64) error); ok {
		r1 = returnFunc(p, off)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_WriteAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteAt'
type MockWriter_WriteAt_Call struct {
	*mock.Call
}

// WriteAt is a helper method to define mock.On call
//   - p []byte
//   - off int64
func (_e *MockWriter_Expecter) WriteAt(p interface{}, off interface{}) *MockWriter_WriteAt_Call {
	return &MockWriter_WriteAt_Call{Call: _e.mock.On("WriteAt", p, off)}
}

func (_c *MockWriter_WriteAt_Call) Run(run func(p []byte, off int64)) *MockWriter_WriteAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_WriteAt_Call) Return(n int, err error) *MockWriter_WriteAt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockWriter_WriteAt_Call) RunAndReturn(run func(p []byte, off int64) (int, error)) *MockWriter_WriteAt_Call {
	_c.Call.Return(run)
	return _c
}
